/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/audit-logs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read the audit trail */
    get: operations['AuditController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sign in with email and password */
    post: operations['AuthController_login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Exchange the refresh cookie for a new access token */
    post: operations['AuthController_refresh'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke the current refresh token */
    post: operations['AuthController_logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current user, organization and effective permissions */
    get: operations['AuthController_me'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/google': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Redirect to Google sign-in */
    get: operations['AuthController_startGoogle'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update your own profile */
    patch: operations['UsersController_updateProfile'];
    trace?: never;
  };
  '/api/v1/users/me/password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Change your own password. Signs out every session */
    put: operations['UsersController_changePassword'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List the organization members */
    get: operations['UsersController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read one member */
    get: operations['UsersController_findOne'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Change a member name, role or status */
    patch: operations['UsersController_update'];
    trace?: never;
  };
  '/api/v1/invitations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List the invitations this organization has issued */
    get: operations['InvitationsController_list'];
    put?: never;
    /** Invite someone, and get the link to hand them */
    post: operations['InvitationsController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/invitations/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke an invitation that has not been used */
    delete: operations['InvitationsController_revoke'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/invitations/lookup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Read what an invitation link stands for */
    post: operations['InvitationsController_lookup'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/invitations/accept': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Take up an invitation and open a session */
    post: operations['InvitationsController_accept'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/organization': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read the organization behind this session */
    get: operations['OrganizationsController_current'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Change the name, branding or time zone */
    patch: operations['OrganizationsController_update'];
    trace?: never;
  };
  '/api/v1/categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List categories */
    get: operations['CategoriesController_list'];
    put?: never;
    /** Create a category */
    post: operations['CategoriesController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/categories/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read one category */
    get: operations['CategoriesController_findOne'];
    put?: never;
    post?: never;
    /** Delete a category that has no products */
    delete: operations['CategoriesController_remove'];
    options?: never;
    head?: never;
    /** Rename or reorder a category */
    patch: operations['CategoriesController_update'];
    trace?: never;
  };
  '/api/v1/brands': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List brands */
    get: operations['BrandsController_list'];
    put?: never;
    /** Create a brand */
    post: operations['BrandsController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/brands/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read one brand */
    get: operations['BrandsController_findOne'];
    put?: never;
    post?: never;
    /** Delete a brand that has no products */
    delete: operations['BrandsController_remove'];
    options?: never;
    head?: never;
    /** Rename a brand */
    patch: operations['BrandsController_update'];
    trace?: never;
  };
  '/api/v1/products': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List products, searched and filtered server-side */
    get: operations['ProductsController_list'];
    put?: never;
    /** Create a product */
    post: operations['ProductsController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/products/facets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Distinct origins, subcategories, ages and ABVs, for the filters */
    get: operations['ProductsController_facets'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/products/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read one product */
    get: operations['ProductsController_findOne'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Edit a product, or retire it with isActive: false */
    patch: operations['ProductsController_update'];
    trace?: never;
  };
  '/api/v1/movements': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List movements, filtered and paginated server-side */
    get: operations['MovementsController_list'];
    put?: never;
    /** Open a movement as a draft. Stock is untouched until confirmed */
    post: operations['MovementsController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/movements/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read one movement with its lines */
    get: operations['MovementsController_findOne'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Edit a draft. Lines are replaced wholesale */
    patch: operations['MovementsController_update'];
    trace?: never;
  };
  '/api/v1/movements/{id}/confirm': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Apply the movement to stock and close it */
    post: operations['MovementsController_confirm'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/movements/{id}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Void a movement, returning whatever stock it took */
    post: operations['MovementsController_cancel'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/stock': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Stock on hand, by product */
    get: operations['StockController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/stock/low': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Products at or under their reorder threshold */
    get: operations['StockController_low'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/stock/{productId}/kardex': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** One product ledger, newest first, with the running balance */
    get: operations['StockController_kardex'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/locations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List locations */
    get: operations['LocationsController_list'];
    put?: never;
    /** Create a location */
    post: operations['LocationsController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/locations/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read one location */
    get: operations['LocationsController_findOne'];
    put?: never;
    post?: never;
    /** Delete a location the ledger does not reference */
    delete: operations['LocationsController_remove'];
    options?: never;
    head?: never;
    /** Rename a location, or promote it to default */
    patch: operations['LocationsController_update'];
    trace?: never;
  };
  '/api/v1/movements/{id}/pdf': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Download the movement as a PDF */
    get: operations['DocumentsController_download'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/reports/summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Headline figures for a range, plus where the catalogue stands now */
    get: operations['ReportsController_summary'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/reports/consumption': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** What was dispatched in a range, by product, category or brand */
    get: operations['ReportsController_consumption'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/reports/activity': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Movement volume over time, bucketed in the organization timezone */
    get: operations['ReportsController_activity'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Service and dependency status */
    get: operations['HealthController_check'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    AuditEntity:
      | 'user'
      | 'invitation'
      | 'organization'
      | 'category'
      | 'brand'
      | 'product'
      | 'location'
      | 'movement';
    /** @enum {string} */
    AuditAction:
      | 'user.signed-in'
      | 'user.sign-in-failed'
      | 'user.password-changed'
      | 'user.updated'
      | 'invitation.created'
      | 'invitation.revoked'
      | 'invitation.accepted'
      | 'organization.updated'
      | 'category.created'
      | 'category.updated'
      | 'category.deleted'
      | 'brand.created'
      | 'brand.updated'
      | 'brand.deleted'
      | 'product.created'
      | 'product.updated'
      | 'product.deactivated'
      | 'location.created'
      | 'location.updated'
      | 'location.deleted'
      | 'movement.created'
      | 'movement.updated'
      | 'movement.confirmed'
      | 'movement.cancelled';
    AuditLogActorDto: {
      /** Format: uuid */
      id: string;
      name: string;
      /** Format: email */
      email: string;
    };
    AuditLogDto: {
      /** Format: uuid */
      id: string;
      /** @example movement.confirmed */
      action: components['schemas']['AuditAction'];
      /** @example movement */
      entity: components['schemas']['AuditEntity'];
      entityId: string | null;
      /** @description Flat scalar detail about the change */
      metadata: Record<string, never>;
      ipAddress: string | null;
      /** Format: date-time */
      createdAt: string;
      /** @description Null for system actions */
      user: components['schemas']['AuditLogActorDto'] | null;
    };
    PageMetaDto: {
      /** @description Which page this is, 1-based */
      page: number;
      /** @description How many items a full page holds */
      pageSize: number;
      /** @description Items matching the filters across every page */
      total: number;
      /** @description How many pages the total splits into. Never below 1 */
      pageCount: number;
      /** @description Number of items on this page */
      count: number;
    };
    AuditLogPageDto: {
      data: components['schemas']['AuditLogDto'][];
      meta: components['schemas']['PageMetaDto'];
    };
    LoginDto: {
      /**
       * Format: email
       * @example admin@beverageledger.local
       */
      email: string;
      /** Format: password */
      password: string;
    };
    /** @enum {string} */
    UserRole: 'PLATFORM_ADMIN' | 'ORG_ADMIN' | 'MANAGER' | 'OPERATOR';
    /** @enum {string} */
    UserStatus: 'ACTIVE' | 'INVITED' | 'SUSPENDED';
    SessionUserDto: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email: string;
      name: string;
      avatarUrl: string | null;
      role: components['schemas']['UserRole'];
      status: components['schemas']['UserStatus'];
    };
    SessionDto: {
      /** @description Bearer token. The frontend keeps it in memory, never in storage */
      accessToken: string;
      /** @description Seconds until the access token expires */
      expiresIn: number;
      user: components['schemas']['SessionUserDto'];
    };
    SessionOrganizationDto: {
      /** Format: uuid */
      id: string;
      name: string;
      slug: string;
      logoUrl: string | null;
      timezone: string;
    };
    /**
     * @description Effective permissions. The UI hides what is not listed; the API still enforces it
     * @enum {string}
     */
    Permission:
      | 'movement:read'
      | 'movement:create-outbound'
      | 'movement:create-inbound'
      | 'movement:create-adjustment'
      | 'movement:create-transfer'
      | 'movement:cancel'
      | 'stock:read'
      | 'report:read'
      | 'catalog:manage'
      | 'user:manage'
      | 'organization:manage'
      | 'audit:read';
    CurrentSessionDto: {
      user: components['schemas']['SessionUserDto'];
      organization: components['schemas']['SessionOrganizationDto'];
      /** @description Effective permissions. The UI hides what is not listed; the API still enforces it */
      permissions: components['schemas']['Permission'][];
    };
    UpdateProfileDto: {
      /** @example Ana Restrepo */
      name?: string;
      /** Format: uri */
      avatarUrl?: string | null;
    };
    UserDto: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email: string;
      name: string;
      avatarUrl: string | null;
      role: components['schemas']['UserRole'];
      status: components['schemas']['UserStatus'];
      /** Format: date-time */
      emailVerifiedAt: string | null;
      /** Format: date-time */
      lastLoginAt: string | null;
      /** Format: date-time */
      createdAt: string;
    };
    ChangePasswordDto: {
      /**
       * Format: password
       * @description Required unless the account has no password yet, as with Google-only users
       */
      currentPassword?: string;
      /**
       * Format: password
       * @description At least 12 characters, with lowercase, uppercase and a digit
       * @example Inventario2026!
       */
      newPassword: string;
    };
    UserPageDto: {
      data: components['schemas']['UserDto'][];
      meta: components['schemas']['PageMetaDto'];
    };
    UpdateUserDto: {
      name?: string;
      role?: components['schemas']['UserRole'];
      status?: components['schemas']['UserStatus'];
    };
    InvitationDto: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email: string;
      role: components['schemas']['UserRole'];
      /** Format: date-time */
      expiresAt: string;
      /** Format: date-time */
      acceptedAt: string | null;
      /** Format: date-time */
      revokedAt: string | null;
      /** @description Who sent it */
      invitedByName: string;
      /** Format: date-time */
      createdAt: string;
    };
    InvitationPageDto: {
      data: components['schemas']['InvitationDto'][];
      meta: components['schemas']['PageMetaDto'];
    };
    CreateInvitationDto: {
      /** Format: email */
      email: string;
      /** @example OPERATOR */
      role: components['schemas']['UserRole'];
    };
    IssuedInvitationDto: {
      invitation: components['schemas']['InvitationDto'];
      /** @description The link to pass to the invitee. Shown once */
      acceptUrl: string;
    };
    InvitationTokenDto: {
      /** @description The token from the invitation link */
      token: string;
    };
    InvitationPreviewDto: {
      /** Format: email */
      email: string;
      role: components['schemas']['UserRole'];
      /** @description The organization being joined */
      organizationName: string;
      /** Format: date-time */
      expiresAt: string;
    };
    AcceptInvitationDto: {
      /** @description The token from the invitation link */
      token: string;
      /** @example Ana Restrepo */
      name: string;
      /**
       * Format: password
       * @description At least 12 characters, with lowercase, uppercase and a digit
       * @example Inventario2026!
       */
      password: string;
    };
    OrganizationDto: {
      /** Format: uuid */
      id: string;
      /** @description Trading name. Heads the interface and every document */
      name: string;
      slug: string;
      /** @description Registered name, for documents that need it */
      legalName: string | null;
      logoUrl: string | null;
      /** @description IANA time zone. Reports bucket by it */
      timezone: string;
      /** Format: date-time */
      createdAt: string;
    };
    UpdateOrganizationDto: {
      name?: string;
      legalName?: string;
      /** Format: uri */
      logoUrl?: string;
      /**
       * @description IANA time zone
       * @example America/Bogota
       */
      timezone?: string;
    };
    CategoryDto: {
      /** Format: uuid */
      id: string;
      name: string;
      /** @description Derived from the name; what the category is unique by */
      slug: string;
      /** @description Ascending display order */
      sortOrder: number;
      /** @description How many products reference it */
      productCount: number;
    };
    CategoryPageDto: {
      data: components['schemas']['CategoryDto'][];
      meta: components['schemas']['PageMetaDto'];
    };
    CreateCategoryDto: {
      /** @example Ron */
      name: string;
      /** @default 0 */
      sortOrder: number;
    };
    UpdateCategoryDto: {
      name?: string;
      sortOrder?: number;
    };
    BrandDto: {
      /** Format: uuid */
      id: string;
      name: string;
      /** @description Derived from the name; what the brand is unique by */
      slug: string;
      /** @description How many products reference it */
      productCount: number;
    };
    BrandPageDto: {
      data: components['schemas']['BrandDto'][];
      meta: components['schemas']['PageMetaDto'];
    };
    CreateBrandDto: {
      /** @example Diageo */
      name: string;
    };
    UpdateBrandDto: {
      name: string;
    };
    ProductReferenceDto: {
      /** Format: uuid */
      id: string;
      name: string;
    };
    ProductDto: {
      /** Format: uuid */
      id: string;
      name: string;
      category: components['schemas']['ProductReferenceDto'];
      brand: components['schemas']['ProductReferenceDto'] | null;
      subcategory: string | null;
      /** @description Alcohol by volume, as a percentage */
      abv: number | null;
      origin: string | null;
      age: string | null;
      /** @description Singles per case; normalizes quantities to base units */
      caseSize: number;
      /** @description Reorder threshold. Null means no alert */
      minimumStock: number | null;
      isActive: boolean;
    };
    ProductPageDto: {
      data: components['schemas']['ProductDto'][];
      meta: components['schemas']['PageMetaDto'];
    };
    ProductFacetsDto: {
      origins: string[];
      subcategories: string[];
      ages: string[];
      /** @description Ascending */
      abvs: number[];
    };
    CreateProductDto: {
      /** @example Havana Club 7 Años */
      name: string;
      /** Format: uuid */
      categoryId: string;
      /** Format: uuid */
      brandId?: string | null;
      subcategory?: string;
      abv?: number;
      origin?: string;
      /** @example 7 años */
      age?: string;
      /**
       * @description Singles per case
       * @default 12
       */
      caseSize: number;
      /** @description Reorder threshold, in singles */
      minimumStock?: number;
    };
    UpdateProductDto: {
      name?: string;
      /** Format: uuid */
      categoryId?: string;
      /**
       * Format: uuid
       * @description Null unlinks the brand. Omitted leaves it as it is
       */
      brandId?: string | null;
      subcategory?: string;
      abv?: number;
      origin?: string;
      age?: string;
      /** @description Reorder threshold, in singles */
      minimumStock?: number;
      /** @description Deactivate instead of deleting: the ledger references it */
      isActive?: boolean;
    };
    /** @enum {string} */
    MovementType: 'INBOUND' | 'OUTBOUND' | 'ADJUSTMENT' | 'TRANSFER';
    /** @enum {string} */
    MovementStatus: 'DRAFT' | 'CONFIRMED' | 'CANCELLED';
    MovementActorDto: {
      /** Format: uuid */
      id: string;
      name: string;
    };
    MovementSummaryDto: {
      /** Format: uuid */
      id: string;
      /** @example MOV-2026-000042 */
      code: string;
      type: components['schemas']['MovementType'];
      status: components['schemas']['MovementStatus'];
      /** Format: date-time */
      occurredAt: string;
      note: string | null;
      createdBy: components['schemas']['MovementActorDto'];
      /** @description How many lines it has */
      itemCount: number;
    };
    MovementPageDto: {
      data: components['schemas']['MovementSummaryDto'][];
      meta: components['schemas']['PageMetaDto'];
    };
    /** @enum {string} */
    MovementUnit: 'BOTTLE' | 'CASE';
    MovementItemDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      productId: string;
      /**
       * Format: uuid
       * @description Which location this line moves. A transfer writes one line per side
       */
      locationId: string;
      /** @description As captured, in the unit below */
      quantity: number;
      unit: components['schemas']['MovementUnit'];
      /** @description Normalized to singles with the case size. Signed by type */
      quantityBase: number;
      /** @description The product name as it stood when the line was written */
      productNameSnapshot: string;
      brandNameSnapshot: string | null;
    };
    MovementDto: {
      /** Format: uuid */
      id: string;
      /** @example MOV-2026-000042 */
      code: string;
      type: components['schemas']['MovementType'];
      status: components['schemas']['MovementStatus'];
      /**
       * Format: uuid
       * @description The origin on a transfer
       */
      locationId: string;
      /**
       * Format: uuid
       * @description Only a transfer has one
       */
      destinationLocationId: string | null;
      /**
       * Format: date-time
       * @description When it happened
       */
      occurredAt: string;
      /** @description Mandatory on adjustments */
      reason: string | null;
      note: string | null;
      createdBy: components['schemas']['MovementActorDto'];
      /** Format: date-time */
      confirmedAt: string | null;
      /** Format: date-time */
      cancelledAt: string | null;
      /** Format: date-time */
      createdAt: string;
      items: components['schemas']['MovementItemDto'][];
    };
    MovementLineInputDto: {
      /** Format: uuid */
      productId: string;
      /**
       * @description Positive on inbound, outbound and transfer, where the type carries the direction. Signed on an adjustment, which corrects either way
       * @example 6
       */
      quantity: number;
      /** @default BOTTLE */
      unit: components['schemas']['MovementUnit'];
    };
    CreateMovementDto: {
      type: components['schemas']['MovementType'];
      /**
       * Format: uuid
       * @description Defaults to the default location. The origin on a transfer
       */
      locationId?: string;
      /**
       * Format: uuid
       * @description Required on a transfer, and rejected on every other type
       */
      destinationLocationId?: string;
      /**
       * Format: date-time
       * @description When it happened, which need not be now. Defaults to now
       */
      occurredAt?: string;
      /** @description Mandatory on adjustments */
      reason?: string;
      note?: string;
      items: components['schemas']['MovementLineInputDto'][];
    };
    UpdateMovementDto: {
      /** Format: date-time */
      occurredAt?: string;
      reason?: string;
      note?: string;
      items?: components['schemas']['MovementLineInputDto'][];
    };
    CancelMovementDto: {
      /** @description Why it is being voided. Kept on the audit trail */
      reason: string;
    };
    StockLevelDto: {
      /** Format: uuid */
      productId: string;
      productName: string;
      brandName: string | null;
      categoryName: string;
      /** @description On hand, in singles */
      quantityBase: number;
      /** @description Singles per case */
      caseSize: number;
      /** @description Reorder threshold. Null means no alert */
      minimumStock: number | null;
      /** @description Whether it sits at or under the reorder threshold */
      isBelowMinimum: boolean;
    };
    StockPageDto: {
      data: components['schemas']['StockLevelDto'][];
      meta: components['schemas']['PageMetaDto'];
    };
    KardexEntryDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      movementId: string;
      /** @example MOV-2026-000042 */
      movementCode: string;
      type: components['schemas']['MovementType'];
      /** Format: date-time */
      occurredAt: string;
      quantity: number;
      unit: components['schemas']['MovementUnit'];
      /** @description Signed change in singles */
      quantityBase: number;
      /** @description On hand after this line */
      balanceAfter: number;
    };
    KardexPageDto: {
      data: components['schemas']['KardexEntryDto'][];
      meta: components['schemas']['PageMetaDto'];
    };
    LocationDto: {
      /** Format: uuid */
      id: string;
      /** @example Bodega principal */
      name: string;
      /** @description Where a movement lands when it names no location */
      isDefault: boolean;
      /** @description Movements that reference it. A used location cannot be deleted */
      movementCount: number;
    };
    LocationPageDto: {
      data: components['schemas']['LocationDto'][];
      meta: components['schemas']['PageMetaDto'];
    };
    CreateLocationDto: {
      /** @example Barra */
      name: string;
      /**
       * @description Makes this the default and demotes the current one
       * @default false
       */
      isDefault: boolean;
    };
    UpdateLocationDto: {
      name?: string;
      /** @description Only promoting is possible: demoting would leave the organization without one */
      isDefault?: boolean;
    };
    ReportRangeEchoDto: {
      /** Format: date-time */
      from: string;
      /** Format: date-time */
      to: string;
    };
    SummaryReportDto: {
      /** @description The range actually applied */
      range: components['schemas']['ReportRangeEchoDto'];
      /** @description Confirmed movements in the range */
      movements: number;
      inboundMovements: number;
      outboundMovements: number;
      adjustmentMovements: number;
      /** @description Singles received */
      unitsIn: number;
      /** @description Singles dispatched, as a positive number */
      unitsOut: number;
      /** @description Net singles added or removed by adjustments */
      unitsAdjusted: number;
      /** @description Distinct products that moved in the range */
      productsMoved: number;
      /** @description Singles on hand right now, across every location */
      unitsOnHand: number;
      /** @description Active products in the catalogue right now */
      activeProducts: number;
      /** @description Active products at or under their reorder threshold right now */
      productsBelowMinimum: number;
    };
    ConsumptionRowDto: {
      /** Format: uuid */
      id: string;
      name: string;
      /** @description Singles dispatched, as a positive number */
      quantityBase: number;
      /** @description How many movements it appeared in */
      movementCount: number;
    };
    ConsumptionReportDto: {
      range: components['schemas']['ReportRangeEchoDto'];
      /** @enum {string} */
      groupBy: 'product' | 'category' | 'brand';
      data: components['schemas']['ConsumptionRowDto'][];
    };
    ActivityRowDto: {
      /**
       * Format: date-time
       * @description Start of the period
       */
      period: string;
      movements: number;
      unitsIn: number;
      /** @description Singles dispatched, as a positive number */
      unitsOut: number;
    };
    ActivityReportDto: {
      range: components['schemas']['ReportRangeEchoDto'];
      /** @enum {string} */
      granularity: 'day' | 'week' | 'month';
      data: components['schemas']['ActivityRowDto'][];
    };
    HealthDependenciesDto: {
      /** @enum {string} */
      database: 'up' | 'down';
    };
    HealthResponseDto: {
      /** @enum {string} */
      status: 'ok' | 'degraded';
      /** @description Seconds since the process started */
      uptimeSeconds: number;
      /** Format: date-time */
      timestamp: string;
      dependencies: components['schemas']['HealthDependenciesDto'];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AuditController_list: {
    parameters: {
      query?: {
        /** @description 1-based page number */
        page?: number;
        /** @description How many items a page holds */
        pageSize?: number;
        entity?: components['schemas']['AuditEntity'];
        /** @description Id of the audited record, to follow one thing over time */
        entityId?: string;
        action?: components['schemas']['AuditAction'];
        /** @description Who performed the action */
        userId?: string;
        from?: string;
        to?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuditLogPageDto'];
        };
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SessionDto'];
        };
      };
      /** @description Invalid credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Rate limit exceeded */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SessionDto'];
        };
      };
      /** @description Missing, expired or replayed refresh token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Rate limit exceeded */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Rate limit exceeded */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CurrentSessionDto'];
        };
      };
      /** @description Rate limit exceeded */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_startGoogle: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Rate limit exceeded */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_updateProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateProfileDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserDto'];
        };
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordDto'];
      };
    };
    responses: {
      /** @description Password changed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The current password is missing */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_list: {
    parameters: {
      query?: {
        /** @description 1-based page number */
        page?: number;
        /** @description How many items a page holds */
        pageSize?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserPageDto'];
        };
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserDto'];
        };
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No such user in this organization */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserDto'];
        };
      };
      /** @description The change would leave the organization without an admin */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  InvitationsController_list: {
    parameters: {
      query?: {
        /** @description 1-based page number */
        page?: number;
        /** @description How many items a page holds */
        pageSize?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InvitationPageDto'];
        };
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  InvitationsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateInvitationDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['IssuedInvitationDto'];
        };
      };
      /** @description Insufficient permissions, or a role that cannot be given */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Already a member, or already invited */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  InvitationsController_revoke: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No such invitation in this organization */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Already used or already revoked */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  InvitationsController_lookup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['InvitationTokenDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InvitationPreviewDto'];
        };
      };
      /** @description Unknown, spent, revoked or expired */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  InvitationsController_accept: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AcceptInvitationDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SessionDto'];
        };
      };
      /** @description Unknown, spent, revoked or expired */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description That email already belongs to a member */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  OrganizationsController_current: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrganizationDto'];
        };
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  OrganizationsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateOrganizationDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrganizationDto'];
        };
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CategoriesController_list: {
    parameters: {
      query?: {
        /** @description 1-based page number */
        page?: number;
        /** @description How many items a page holds */
        pageSize?: number;
        /** @description Matches part of the name, case-insensitively */
        search?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryPageDto'];
        };
      };
    };
  };
  CategoriesController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCategoryDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryDto'];
        };
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The name is already in use */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CategoriesController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryDto'];
        };
      };
      /** @description No such category in this organization */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CategoriesController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Products still reference it */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CategoriesController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateCategoryDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryDto'];
        };
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BrandsController_list: {
    parameters: {
      query?: {
        /** @description 1-based page number */
        page?: number;
        /** @description How many items a page holds */
        pageSize?: number;
        /** @description Matches part of the name, case-insensitively */
        search?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BrandPageDto'];
        };
      };
    };
  };
  BrandsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateBrandDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BrandDto'];
        };
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The name is already in use */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BrandsController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BrandDto'];
        };
      };
      /** @description No such brand in this organization */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BrandsController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Products still reference it */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BrandsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateBrandDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BrandDto'];
        };
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProductsController_list: {
    parameters: {
      query?: {
        /** @description 1-based page number */
        page?: number;
        /** @description How many items a page holds */
        pageSize?: number;
        /** @description Matches part of the name, case-insensitively */
        search?: string;
        categoryId?: string;
        brandId?: string;
        /** @description Exact match, from the values in /products/facets */
        origin?: string;
        /** @description Exact match, from the values in /products/facets */
        subcategory?: string;
        /** @description Exact match, from the values in /products/facets */
        age?: string;
        abv?: number;
        status?: 'active' | 'inactive' | 'all';
        /** @description Comma-separated product ids. Narrows the page to those products */
        productIds?: string;
        sort?: 'name' | '-name' | '-createdAt' | 'createdAt';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProductPageDto'];
        };
      };
    };
  };
  ProductsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateProductDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProductDto'];
        };
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The name is already in use */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProductsController_facets: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProductFacetsDto'];
        };
      };
    };
  };
  ProductsController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProductDto'];
        };
      };
      /** @description No such product in this organization */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProductsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateProductDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProductDto'];
        };
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MovementsController_list: {
    parameters: {
      query?: {
        /** @description 1-based page number */
        page?: number;
        /** @description How many items a page holds */
        pageSize?: number;
        /** @description Matches part of the movement code, case-insensitively */
        search?: string;
        type?: components['schemas']['MovementType'];
        status?: components['schemas']['MovementStatus'];
        /** @description Only movements touching this product */
        productId?: string;
        createdByUserId?: string;
        /** @description Movements touching this location, on either side of a transfer */
        locationId?: string;
        from?: string;
        to?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MovementPageDto'];
        };
      };
    };
  };
  MovementsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateMovementDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MovementDto'];
        };
      };
      /** @description Unknown product, missing reason or wrong quantity sign */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description You may not record this type of movement */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MovementsController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MovementDto'];
        };
      };
      /** @description No such movement in this organization */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MovementsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateMovementDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MovementDto'];
        };
      };
      /** @description You may not record this type of movement */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description It is no longer a draft */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MovementsController_confirm: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MovementDto'];
        };
      };
      /** @description A line would leave stock below zero */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description You may not record this type of movement */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description It is no longer a draft */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MovementsController_cancel: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CancelMovementDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MovementDto'];
        };
      };
      /** @description Reverting it would leave stock below zero */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description It is already cancelled */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  StockController_list: {
    parameters: {
      query?: {
        /** @description 1-based page number */
        page?: number;
        /** @description How many items a page holds */
        pageSize?: number;
        /** @description Matches part of the product name */
        search?: string;
        categoryId?: string;
        /** @description Defaults to the default location */
        locationId?: string;
        /** @description Comma-separated product ids. Narrows the page to those products */
        productIds?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StockPageDto'];
        };
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  StockController_low: {
    parameters: {
      query?: {
        /** @description Defaults to the default location */
        locationId?: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StockLevelDto'][];
        };
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  StockController_kardex: {
    parameters: {
      query?: {
        /** @description 1-based page number */
        page?: number;
        /** @description How many items a page holds */
        pageSize?: number;
        /** @description Defaults to the default location */
        locationId?: string;
      };
      header?: never;
      path: {
        productId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['KardexPageDto'];
        };
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No such product in this organization */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  LocationsController_list: {
    parameters: {
      query?: {
        /** @description 1-based page number */
        page?: number;
        /** @description How many items a page holds */
        pageSize?: number;
        /** @description Matches part of the name, case-insensitively */
        search?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LocationPageDto'];
        };
      };
    };
  };
  LocationsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateLocationDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LocationDto'];
        };
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The name is already in use */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  LocationsController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LocationDto'];
        };
      };
      /** @description No such location in this organization */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  LocationsController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description It is the default, or movements reference it */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  LocationsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateLocationDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LocationDto'];
        };
      };
      /** @description Demoting a default is not allowed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DocumentsController_download: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The document */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/pdf': string;
        };
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No such movement in this organization */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ReportsController_summary: {
    parameters: {
      query?: {
        /** @description Defaults to 30 days ago */
        from?: string;
        /** @description Defaults to now */
        to?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SummaryReportDto'];
        };
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ReportsController_consumption: {
    parameters: {
      query?: {
        /** @description Defaults to 30 days ago */
        from?: string;
        /** @description Defaults to now */
        to?: string;
        groupBy?: 'product' | 'category' | 'brand';
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConsumptionReportDto'];
        };
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ReportsController_activity: {
    parameters: {
      query?: {
        /** @description Defaults to 30 days ago */
        from?: string;
        /** @description Defaults to now */
        to?: string;
        granularity?: 'day' | 'week' | 'month';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActivityReportDto'];
        };
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  HealthController_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponseDto'];
        };
      };
      /** @description A dependency is not responding */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
